[package]
name = "hash-collider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dev-dependencies]
num_cpus = "1.13.1"
ahash = "0.7.6"

[profile.release]
debug = true
